### ISSUE TITLE
No booteable device error

### ISSUE THREAD

**Issue by ghost** [pritamzope/OS#1]
When I run run.sh, I get this error in QEMU
![Imgur](https://i.imgur.com/NUk9Zmb.png)
BTW, I am in the WSL (Windows subsystem for Linux)

**Comment by pritamzope** [comment]
could you please provide the linux disto that you have installed ?

**Comment by konniskatt** [comment]
Is Ubuntu under the Windows subsystem for linux

**Comment by pritamzope** [comment]
updated run.sh script.
Tested on Ubuntu WSL with gcc-5,6,7,8 
checkout issue 2 here https://github.com/pritamzope/OS/issues/2
