### ISSUE TITLE
I am unable to load PE

### ISSUE THREAD

**Issue by motosoftos** [pritamzope/OS#10]
@pritamzope , I am having no idea on the Code to load PE. Please help me. Thanks in advance.

**Comment by motosoftos** [comment]
Some one please reply. Pls

**Comment by motosoftos** [comment]
@pritamzope come on!!

**Comment by AtieP** [comment]
@motosoftos What do you mean with PE?

**Comment by motosoftos** [comment]
PE are portable executables like EXE in MS
I have resolved it myself, but with bin files not PE.
Thx

**Comment by sasdallas** [comment]
Pro tip for anyone who would want to do this:
You'll need to understand OSes very well and have a very strong and ready base. This person, clearly, did not.
