### ISSUE TITLE
How do I create a bootloader that loads the OS

### ISSUE THREAD

**Issue by okyanusoz** [pritamzope/OS#14]
I know I need to enter Protected Mode etc. but I don't see any code when I lookup on the web. Can someone give a sample code of a full bootloader in Assembly? Also, I was using GRUB, but I want to create my own. I need to load an elf_i386 file.

**Comment by sasdallas** [comment]
@okyanusoz To clarify, do you mean something like an MBR? It’s quite easy to write one of those, take a look here: [link](https://wiki.osdev.org/MBR_(x86)#MBR_Bootstrap) if so.

If you are talking about something like a multi boot loader, that is included in the repo. If you are talking about something else, please tell me. I’m not sure how you would load an elf_i386 file.

Can you send over how you are compiling the code and/or the code?
