### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by ghost** [pritamzope/OS#16]
https://www.github.com/pritamzope/OS/tree/master/CPUInfo%2Fcpu_info_c%2Frun.sh

The first command to compile the boot.s fails. It says --32 not an option.

**Comment by xing1357** [comment]
Can you give some more details in the error?

**Comment by ajh123** [comment]
If your on MacOs then you need an i386-elf cross compiler

**Comment by pritamzope** [comment]
check which option you compiler is providing to assemble source code in 32 bit format.
    $ man as
