### ISSUE TITLE
TicTacToe: box.o:(.bss+0x0): multiple definition of `vga_buffer'

### ISSUE THREAD

**Issue by arteze** [pritamzope/OS#18]
At execute:

```sh
./run.sh
```

Result:

```sh
box.o:(.bss+0x0): multiple definition of `vga_buffer'
kernel.o:(.bss+0x4): first defined here
tic_tac_toe.o:(.bss+0x18): multiple definition of `vga_buffer'
kernel.o:(.bss+0x4): first defined here
grub-file: error: cannot open `TicTacToe.bin': No such file or directory.
cp: cannot stat 'TicTacToe.bin': No such file or directory
```

Versions:

 - GNU assembler version 2.26.20160125
 - GNU bash, version 5.0.17(1)-release (x86_64-slackware-linux-gnu)
 - gcc (GCC) 10.2.0
 - GNU ld version 2.26.20160125

**Comment by arteze** [comment]
The same happens in all projects, for example in Pong-Game.
```sh
/OS-master/Pong-Game# ./run.sh 
vga.o:(.bss+0x0): multiple definition of `vga_buffer'
kernel.o:(.bss+0x0): first defined here
bitmap.o:(.bss+0x0): multiple definition of `vga_buffer'
kernel.o:(.bss+0x0): first defined here
pong.o:(.bss+0x4): multiple definition of `vga_buffer'
kernel.o:(.bss+0x0): first defined here
```

**Comment by xing1357** [comment]
try running the linker script with the params `--allow-multiple-definition` . I think he is declaring variables in the header files.

**Comment by arteze** [comment]
Thanks, it works for me.

I had seen that they use the parameter in the GCC with `-Wl,--allow-multiple-definition`, I never imagined that it would go in the _linker (ld)_, it is good to know.

**Comment by xing1357** [comment]
Yeah, I hope he can update the header file.

**Comment by arteze** [comment]
Yes, I was able to compile it, as you can see in the image, it is running, and the issue can be closed but when I try to close it with `Close with comment`, it remains open.

**Comment by xing1357** [comment]
I think @pritamzope should do that now.

**Comment by pritamzope** [comment]
issue fixed, please check
