### ISSUE TITLE
How to set cursor location?

### ISSUE THREAD

**Issue by Hampusm** [pritamzope/OS#4]
Title says it all. @pritamzope

**Comment by Hampusm** [comment]
@pritamzope come on

**Comment by pritamzope** [comment]
https://github.com/pritamzope/OS/tree/master/Bootloader/Sample

**Comment by AtieP** [comment]
@Hampusm To get cursor position, use `ah = 03 | int 10h`. This returns:
* DL: Horizontal position 
* DH: Vertical position
* CH: Start of scan line
* CL: End of scan line

Hope this helps.

**Comment by AtieP** [comment]
Ah sorry, I readed "how to GET cursor position" 😅 
Use `ah = 02 | int 10h` to set cursor position. You need to include this parameters:
* BH: Page (set it to 0)
* DH: Vertical position
* DL: Horizontal position
😅

**Comment by Hampusm** [comment]
@AtieP Oh my god thank you! Finally! Took 2 years but still thank you.

**Comment by AtieP** [comment]
No problem @Hampusm :smiley:
