### ISSUE TITLE
Error occur when I'm compiling the .asm file

### ISSUE THREAD

**Issue by WinsDominoes** [pritamzope/OS#6]
Hello, I have an error while compiling the .asm file to .bin or .iso 
This is the error: 

WinOS.asm:161: error: TIMES value -5 is negative

I downloaded your source code of the Hello World Extended OS Version in your blogger site. And the error occur in this line: 
`;///////////////////////////////////////////
    ; boot loader magic number
    times ((0x200 - 2) - ($ - $$)) db 0x00     ;set 512 bytes for boot sector which are necessary
    dw 0xAA55                                  ; boot signature 0xAA & 0x55`

Please help because, I cannot convert it into .iso or .bin. Linux Distro: Linux Mint Cinnamon 19 Thank you.﻿

**Comment by pritamzope** [comment]
Well i didn't get this error on my machine. This line tells the assembler how many bytes required to build assemble in that number of bytes(which are 512 bytes here for boot signature).
Have you tried to assemble simple helloworld code ?

**Comment by WinsDominoes** [comment]
Not yet but, today I will try @pritamzope

**Comment by WinsDominoes** [comment]
I tried already with the "Hello World!" Code and it worked. But, the Extended version has an error

**Comment by WinsDominoes** [comment]
I already tried the Hello World Code, It worked, but I also try again the Extended Version. It worked also.
