### ISSUE TITLE
Error:'run.sh: 20: qemu-system-x86_64: not found', by the way i'm using kali linux on virtualbox(Debian-64)

### ISSUE THREAD

**Issue by harshsingh8** [pritamzope/OS#8]

**Comment by harshsingh8** [comment]
Ok, I resolved it...
At first i ran the command in terminal 
"sudo apt-get install qemu-system" to install qemu
then in run.sh I replaced "qemu-system-x86_64 -cdrom MyOS.iso" with "qemu-system-i386 -cdrom MyOS.iso" and it worked.

**Comment by pritamzope** [comment]
sudo apt-get install qemu-system-x86
or
sudo apt-get install qemu-system-x86_64

if x86_64 is not available on your system then replace it in run.sh script
